name: Change Directory
description: Changes the working directory on post-checkout
author: https://github.com/reidab
requirements: []
configuration:
  properties:
    subdir:
      type: string
  required:
    - subdir
